name: close duplicate issue

on:
  issues:
    types:
      - labeled

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'duplicate'

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: close out issue
        env:
          GH_TOKEN: ${{ github.token }}
        run: | 
          gh issue close ${{ github.event.issue.number }} -c "Issue marked as duplicate, closing" -R ${{ github.repository }}

