name: "Close stale issues"
on:
  repository_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3.0.14
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'No updates in 1 day'
        stale-pr-message: 'No updates in 1 day'
        stale-issue-label: 'stale'
        exempt-issue-labels: 'documentation,enhancement,bug'
        stale-pr-label: 'stale'
        exempt-pr-labels: 'documentation,enhancement,bug'
        days-before-stale: 1
        days-before-close: 1
